### ISSUE TITLE
unable to convert json dashboard to jsonnet

### ISSUE THREAD

**Issue by haarchri** [cznewt/jsonnet-utils#5]
hello, 
i facing an issue after setup jsonnet-utils - any idea what is the problem ??

```
jsonnet-utils-grafana-convert --source-path=dashboards --build-path ./jsonnet-utils/build
2020-12-13 13:30:23,676 [INFO ]  Searching path `dashboards` for JSON dashboards to convert ...
Traceback (most recent call last):
  File "/usr/local/bin/jsonnet-utils-grafana-convert", line 11, in <module>
    load_entry_point('jsonnet-utils==0.1', 'console_scripts', 'jsonnet-utils-grafana-convert')()
  File "/usr/local/lib/python3.7/site-packages/click-8.0.0a1-py3.7.egg/click/core.py", line 1025, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click-8.0.0a1-py3.7.egg/click/core.py", line 955, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click-8.0.0a1-py3.7.egg/click/core.py", line 1279, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click-8.0.0a1-py3.7.egg/click/core.py", line 710, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jsonnet_utils-0.1-py3.7.egg/jsonnet_utils/cli.py", line 29, in dashboard_convert
  File "/usr/local/lib/python3.7/site-packages/jsonnet_utils-0.1-py3.7.egg/jsonnet_utils/grafana_dashboard.py", line 404, in convert_dashboards
  File "/usr/local/lib/python3.7/site-packages/jsonnet_utils-0.1-py3.7.egg/jsonnet_utils/grafana_dashboard.py", line 264, in parse_dashboard
KeyError: 'rows'
```

**Comment by matthiasantierens** [comment]
I have the same issue. I am running python 3.9 in a virtual env with all requirements installed.

**Comment by haarchri** [comment]
think here is no one who takes care :/
